### PR TITLE
🎉 Milestone 1. Rails API to generate a random greeting

### PR DESCRIPTION
**Pull request by indigodavid**
# 🎉 Milestone 1. Rails API to generate a random greeting

For this milestone, the following features have been implemented:

## API Endpoints

`api/v1/hello` => GET => Returns a random greeting stored in the database
`api/v1/greetings` => GET => Returns the greetings stored in the database

## Seed data

Five greetings stored to be randomly displayed:

Aló Aló!
Ahoy Ahoy
Hello World!
Konnichiwa
Hola mundo

## Deployment

[Heroku](https://random-greeting-dvc.herokuapp.com/api/v1/hello)

## React Frontend PR

[Github](https://github.com/indigodavid/hello_react_rails_frontend/pull/1)

### CODE REVIEW

**Review by AnselemOdims — COMMENTED** [review]
# Invalid Request 🛑 
You have been doing very good work on this project but unfortunately, I can not proceed with the review as there are some discrepancies. Check below for details.

- Some checks are failing. Please ensure that all tests pass before asking for another review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by indigodavid** [comment]
@AnselemOdims Thank you for letting me know. I tried earlier today to deploy the app using Netlify, but it didn't allow PostgreSQL. I forgot to remove that deployment.

Best regards and happy coding!

**Review by CollinsTatang — APPROVED** [review]
# Approved 👏  
### **Highlights 🚀 :heavy_check_mark: :heavy_check_mark:** 

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
image



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by indigodavid** [comment]
@CollinsTatang Tank you for your kind review. I'll merge my feature right away.

Best regards and happy coding! 💻 😀

**Pull request merged**
